gromos:debian-12:configure:
  extends:
    - .gromos:base:configure
    - .use-openmp
    - .use-share
  image: ${CI_REGISTRY}/gromos/gromosplspls/gromos-debian-12
  variables:
    BUILD_DIR: build

gromos:debian-12:build:
  extends:
    - .gromos:base:build
    - .use-openmp
    - .use-share
  image: ${CI_REGISTRY}/gromos/gromosplspls/gromos-debian-12
  variables:
    BUILD_DIR: build
    BIN_PATH: ${BUILD_DIR}/bin
  needs:
    - job: gromos:debian-12:configure

gromos:debian-12:ana_test:
  extends:
    - .gromos:base:ana_test
  image: ${CI_REGISTRY}/gromos/gromosplspls/gromos-debian-12
  variables:
    BUILD_DIR: build
    BIN_PATH: ${CI_PROJECT_DIR}/${BUILD_DIR}/bin
    TEST_REPO: ${CI_PROJECT_DIR}/gromos_test_files/
  needs:
    - job: gromos:debian-12:build

